clone_depth: 1

environment:
  nodejs_version: "8"
  access_token:
    secure: TF+cEX3UUey+Sr8GDGZviO2HICJN3WdECvCpVZtEPbBY9UWpBX7bd4ibyd9C0eLG

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm install hexo-cli -g

build_script:
  - hexo generate

artifacts:
  - path: public

on_success:
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "%STATIC_SITE_USER%`n"
  - git config --global credential.helper store  
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git config --global user.password "%GIT_USER_PASSWORD%"
  - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%\static-site
  - cd %TEMP%\static-site
  - del * /f /q
  - for /d %%p IN (*) do rmdir "%%p" /s /q
  - SETLOCAL EnableDelayedExpansion & robocopy "%APPVEYOR_BUILD_FOLDER%\public" "%TEMP%\static-site" /e & IF !ERRORLEVEL! EQU 1 (exit 0) ELSE (IF !ERRORLEVEL! EQU 3 (exit 0) ELSE (exit 1))
  - git add -A
  - git commit -m "Update Static Site" 
  - git push origin %TARGET_BRANCH%
  - appveyor AddMessage "Static Site Updated"
